spring:
  application:
    name: AG
    
  cloud:
    gateway:
      routes:
        - id: restAPI
          uri: lb://restAPI
          predicates:
            - Path=/employees/**

        - id: datajpa
          uri: lb://datajpa
          predicates:
            - Path=/api/**

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
